disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - todo
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources

line_length: 140
file_length: 600
type_body_length: 250
identifier_name:
  min_length: 2