branches:
  only:
    - master
osx_image: xcode9
language: objective-c
env:
  matrix:
    - FASTLANE_TARGET="ios"
install: true
before_script:
  - gem update fastlane
script:
  - set -o pipefail
  - fastlane ${FASTLANE_TARGET} test
